### ISSUE TITLE
Story: Folders on home page 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#101]
## As a user, I want to be able to see my folders on my home page, so I can access them easily. 

- **Number of story points:** 3
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 5 hours 

### Tasks TO DO: 

- [x] Load folders list to the home page 
- [x] Display the folders to the view in the appropriate section

### Related to this story 

- commit: #120 

### Unit test

- commit: #120

### UI test

- commit: #120 

### Demo steps 

0. Create a folder (see demo steps in #45)
1. Open side menu
2. Click on "Home" 
3. Created folder will appear under the "Folders" section

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by williamkingbede** [comment]
UI test successfully passed
![capture d ecran 51](https://user-images.githubusercontent.com/25252961/38781101-76d85d8e-40ae-11e8-9477-b70d5a08415d.png)

**Comment by guipadua** [comment]
Demoed and it works. Has unit test. Has to fix the open in the home page because only show the first one.

**Comment by ghost** [comment]
Issue to show folders fixed in #124.
