### ISSUE TITLE
Story: Home page view

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#102]
## As a user, I want a user-friendly home page, so I can have a lot grouped into one page.  

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Medium
- _**Estimation of the ideal time**_ : 5 hours

### Tasks TO DO: 

- [x] Have the home page tab in the menue. 
- [x] Have the home page created. 
- [x] Have the items selectable (when we click on the episode, be redirected on it; same for folders)

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff 

### Demo Steps

1. Open the side menu
2. Click on the Home tab
3. The Home page opens and displays folders as well as podcasts from favorite, queued... , when added

**Comment by ghost** [comment]
@jiggy357 comment your commits on this story ! thank you :)

**Comment by guipadua** [comment]
Demoed and it looks good.

**Comment by ghost** [comment]
#124
