### ISSUE TITLE
Story: Reorganize the functions and the views 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#115]
## As a user, I want to be able to have a working user-friendly app, so that I have an enjoyable user experience.

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_: 8 hours

### Tasks TO DO: 

- [x] Fix the issue of the remove button on the episodes page
**Demo steps:**  1.  open the Episodes page 
   2. click on the gear icon
   3. click on "Delete download" 
   4. your episode is no longer downloaded 

- [x] Have a different view depending on the page (Download, Favorites and Episodes page), for the options on the episodes. 
**Demo steps:** For episodes page:  1.  open the Episodes page 
   2. click on the gear icon
   3. see all the according buttons "add to queue", "download", "add to favorites", "remove download", "mark as played", "mark as unplayed" 
For downloads page: 1. open the Downloads page 
   2. click on the gear icon
   3. see all the according buttons  "add to queue", ~~"download"~~, "add to favorites", "remove download", "mark as played", "mark as unplayed" 
For favorites page: 1. open the Favorites page
   2. click on the gear icon
   3. see all the according buttons "add to queue", "download", ~~"add to favorites"~~,~~"remove download"~~, "mark as played", "mark as unplayed", "remove from favorites"  

- [x] Fix the Lock/Unlock reversed view in the Queue page. 
**Demo steps:** 1. go to the Queue page 
    2. when you enter the page, the positions are now locked 
    3. click on the lock button
    4. the page is now unlocked and you can change the episodes order on the queue page. 

- ~~Change the icon for add to folder~~ _deleted because it created too many issues_
- [x] Modify the options for the three bars Icon in the Episodes, Queue page, and the Downloads page 
**No demo steps needed, only deleted the unnecessary sort options** 
- [x] Add the Search Bar on the Subscription page 
**Demo steps:** 1. go to the Subscription page
    2. click on the search button 
    3. enter your research
    4. you are now redirected to the search page. 
- [x] Add the Search Bar on the Homepage 
**Demo steps:** Same as subscription's page but from the home page. 
- ~~Fix the issue in the menu bar of the # of subscription and # of episodes.~~ _deleted because of the lack of time due to problems encountered for the other tasks_
- ~~Add the pictures in the Playback History page~~ _deleted because of the lack of time due to problems encountered for the other tasks_

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [ ] Get TA signoff

**Comment by ghost** [comment]
#123

**Comment by ghost** [comment]
![capture d ecran 2018-04-19 a 00 06 21](https://user-images.githubusercontent.com/22198043/38970809-9958851e-4365-11e8-94db-d74d40eb2607.png)
![capture d ecran 2018-04-19 a 00 03 38](https://user-images.githubusercontent.com/22198043/38970810-996b72fa-4365-11e8-8430-68bb77411572.png)
![capture d ecran 2018-04-19 a 00 00 10](https://user-images.githubusercontent.com/22198043/38970812-99838084-4365-11e8-854a-c0cf0e8ffb4d.png)
![capture d ecran 2018-04-18 a 23 59 51](https://user-images.githubusercontent.com/22198043/38971028-ebf211c2-4366-11e8-8548-1c24ca80ef71.png)
