### ISSUE TITLE
Update UML Class Diagram 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#17]
## Update the UML Class Diagram with the new features implemented 

- [x] Story: Episodes page - Organize  #40 
- [x] Story: Add to favorites #27
- [x] Story: Add to queue #26
- [x] Story: Mark as unplayed #39
- [x] Story: Mark as played #24
- [x] Story: Trending tab in side menu #28 

**We have to link each UML class diagrams to its Story**

_**We have to do something more "overview", the Class Diagram in Iteration 1 was too big. We need to organize the Class Diagram and explain a little how the app is working.**_
