### ISSUE TITLE
Feature: Organize podcasts

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#18]
## Feature Description

Implement the ability to 

- "Add to queue" 
- "Mark as played" 
- "Mark as unplayed" 
- "Add to favorites" 
- "Remove"

multiple podcasts via Downloads section 

see AntennaPod's issue:  AntennaPod/AntennaPod#2508

-------------------------------------------------------------------
ADDITIONAL FEATURE: We will add the same abilities to the Episodes page. 

## Feature Stories

- [x] As a user, I want to "Add to queue" Podcasts in my completed downloads, so I can listen to it later when I have the occasion.#26   
- [x] As a user, I want to "Mark as played" Podcasts in my completed downloads, so I don't listen to the same one. #24 
- [x] As a user, I want to "Mark as unplayed" Podcasts in my completed downloads, so I can listen to them again. #39 
- [x] As a user, I want to "Add to favorites" Podcasts in my completed downloads, so I can find Podcasts that I like easily. #27 
- [x] As a user, I want to be able to "Mark as played", "Mark as Unplayed", "Add to queue", "Add to favorites" and "Delete" Podcasts in the Episodes page, so I can organize them as I like. #40 

### Ability to "Add to queue", "Mark as played", "Add to favorites" multiple podcasts via Downloads section

Original Download GUI             |  Original Podcast GUI | New Download GUI Mockup
:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/13441191/35256020-cdf3dc5e-ffbf-11e7-870e-cbcdca81de31.PNG" width="150">  | <img src="https://user-images.githubusercontent.com/13441191/35256042-e96bf750-ffbf-11e7-99b1-8a78dd5c5af3.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35256838-d8f267fc-ffc3-11e7-829e-9f1eaab63ca5.PNG" width="150">

The mock-ups were done by @LeCleric.

**Comment by Raph1105** [comment]
# Feature Mock-ups 

## Ability to "Add to queue", "Mark as played", "Add to favorites" multiple podcasts via Downloads section

Original Download GUI             |  Original Podcast GUI | New Download GUI Mockup
:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/13441191/35256020-cdf3dc5e-ffbf-11e7-870e-cbcdca81de31.PNG" width="150">  | <img src="https://user-images.githubusercontent.com/13441191/35256042-e96bf750-ffbf-11e7-99b1-8a78dd5c5af3.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35256838-d8f267fc-ffc3-11e7-829e-9f1eaab63ca5.PNG" width="150">

The mock-ups were done by @LeCleric.

**Comment by Raph1105** [comment]
https://github.com/FrankSauve/390AntennaPod/issues/3

**Comment by williamkingbede** [comment]
I just checked and apparently when the download of a podcast is completed it is automatically added to queue. So we might have to remove this feature as it is already implemented in some way or we might change to something else like 'remove from queue' (even though I don't see the value in that).

**Comment by FrankSauve** [comment]
@williamkingbede Good point, but it could still be useful if you clear your cue and want to add them back.

**Comment by williamkingbede** [comment]
Ahh okay so in that case we have to find a way to disable the option when it is already in the queue and enable it in the case where it is not already in there.

**Comment by ghost** [comment]
@guipadua Could you validate this feature? thank you!

**Comment by guipadua** [comment]
Good to go. Seems simpler than the other one, but might be a good start, has value and low risk
