### ISSUE TITLE
Story: Mark as played

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#24]
## As a user, I want to "Mark as played" Podcasts in my completed downloads, so I don't listen to the same one.

- **Number of story points:** 3
- **Priority:** Medium
- **Risk:** Low 
- _**Estimation of the ideal time**_: 1 hour 

### Tasks TO DO: 

- [x] Add the button ACTION_MARK_PLAYED from EpisodesApplyActionFragment.java in CompleteDownloadsFragment.java

### Related to this story 

- commit: #38 

### Unit test 

- commit: #57 

### Demo steps 

1. Go to the "Downloads page" by clicking on the tab "Download" in the menu
2. Click on "Completed" 
3. Click on the top right icon (shown in the picture) 

<img width="296" alt="capture d ecran 2018-02-07 a 15 52 15" src="https://user-images.githubusercontent.com/22198043/35941074-17a30a1c-0c1f-11e8-9865-1887d0fe895f.png">

4. Select the episodes you want to mark as unplayed
5. Once you are done with your selection, click on the button "Mark as played" 

<img width="292" alt="mark as played - copie" src="https://user-images.githubusercontent.com/22198043/35952398-ceb429b0-0c4d-11e8-8213-d11b80dc99d3.png">

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by ghost** [comment]
Commit related to this story: #38

**Comment by Raph1105** [comment]
![screen shot 2018-02-21 at 1 30 49 pm](https://user-images.githubusercontent.com/22198043/36498475-602cc0dc-170c-11e8-8ea3-c330818feeba.png)


[View in LucidChart](https://www.lucidchart.com/documents/edit/dda86731-9993-4d8a-be75-6eee946b83eb/0?shared=true&)

**Comment by ghost** [comment]
![screen shot 2018-02-21 at 1 30 49 pm](https://user-images.githubusercontent.com/22198043/36498475-602cc0dc-170c-11e8-8ea3-c330818feeba.png)


[View in LucidChart](https://www.lucidchart.com/documents/edit/dda86731-9993-4d8a-be75-6eee946b83eb/0?shared=true&) 

UML class diagram done by @jiggy357.
