### ISSUE TITLE
Story: Add to favorites

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#27]
## As a user, I want to "Add to favorites" Podcasts, so I can find Podcasts that I like easily.

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_: 2 hours

### Tasks TO DO: 

- [x] create a button "ADD_TO_FAVORITES" in EpisodesApplyActionFragment.java 
- [x] create a view for the "Add to favorites" in episodes_apply_action_fragment.xml 
- [x] add the button to CompletedDowloadsFragment.java

### Related to this story 

- commit: #38 

### Unit test

- commit: #57 

### Demo steps 

1. Go to the "Downloads page" by clicking on the tab "Download" in the menu
2. Click on "Completed" 
3. Click on the top right icon (shown in the picture) 

<img width="296" alt="capture d ecran 2018-02-07 a 15 52 15" src="https://user-images.githubusercontent.com/22198043/35941074-17a30a1c-0c1f-11e8-9865-1887d0fe895f.png">

4. Select the episodes you want to mark as unplayed
5. Once you are done with your selection, click on the button "Add to favorites" 

<img width="292" alt="add to favorites - copie" src="https://user-images.githubusercontent.com/22198043/35952442-f270540a-0c4d-11e8-8687-8b9a35a4e654.png">

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by ghost** [comment]
Commit related to this story: #38

**Comment by ghost** [comment]
Commit related to this story: #57

**Comment by Raph1105** [comment]
![screen shot 2018-02-21 at 1 30 49 pm](https://user-images.githubusercontent.com/22198043/36498475-602cc0dc-170c-11e8-8ea3-c330818feeba.png)


[View in LucidChart](https://www.lucidchart.com/documents/edit/dda86731-9993-4d8a-be75-6eee946b83eb/0?shared=true&)

**Comment by ghost** [comment]
![screen shot 2018-02-21 at 1 30 49 pm](https://user-images.githubusercontent.com/22198043/36498475-602cc0dc-170c-11e8-8ea3-c330818feeba.png)


[View in LucidChart](https://www.lucidchart.com/documents/edit/dda86731-9993-4d8a-be75-6eee946b83eb/0?shared=true&) 

UML class diagram done by @jiggy357.
