### ISSUE TITLE
Story: Trending tab in side menu

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#28]
## As a user, I want to be able to select the Trending tab in the side menu so that I can see trending podcasts.

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 3 hours

### Tasks TO DO: 

- [x] Add Trending tab to the side menu
- [x] Add the appropriate icon next to the Trending tab

### Related to this story: 

- commit: #37 

### Unit test: 

- commit: #37 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff 

### Demo Steps

1. Open the side menu
2. Click on the **Trending** tab
3. The trending page opens and displays the top trending podcasts on itunes

**Comment by FrankSauve** [comment]
Only missing TA signoff

**Comment by williamkingbede** [comment]
![capture d ecran 18](https://user-images.githubusercontent.com/25252961/36515845-54c83400-1749-11e8-80f5-4461c87f7698.png)
[View in LucidChart](https://www.lucidchart.com/documents/edit/1f97e1de-8d06-404c-9a08-1b7743b0cf13/0)

UML class diagram done by @jiggy357.
