### ISSUE TITLE
TO IGNORE 

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#29]
## As a user, I want to be able to view the Trending podcasts so that I can add them to my followed podcasts.

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_ :

### Tasks TO DO: 

- [ ] Get trending podcast from itunes
- [ ] Design UI
- [ ] Redirect to appropriate Activity

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by FrankSauve** [comment]
Should only be one story separated into different tasks
