### ISSUE TITLE
Feature: Create folders

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#30]
## Feature Description

Allow users to put episodes downloaded into folders that they can create and name. Ex: “Comedy” folder, “Non-fiction” folder, etc. 

## Feature Stories

- [x] As a user, I want to be able to create folders (and name them), so that I organize my podcasts. #45
- [x] As a user, I want to be able to add podcasts (from the episodes page) into the folders that I have created, so that I can populate them. #46 (Moved to iteration 5)
- [ ] As a user, I want to be able to see my folders in the menu, so that I can access them easily. #47 (Moved to iteration 5)

### Demo Video
https://youtu.be/UmSpcNy8wGE

**Comment by ghost** [comment]
#46 and #47 are still in progress -- they will be done in iteration 5.
