### ISSUE TITLE
Story: Episodes page - Organize

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#40]
## As a user, I want to be able to "Mark as played", "Mark as Unplayed", "Add to queue", "Add to favorites" and "Delete" Podcasts in the Episodes page, so I can organize them as I like. 

- **Number of story points:** 3
- **Priority:** Medium
- **Risk:**  Low 
- _**Estimation of the ideal time**_ : 1 hour

### Tasks TO DO: 

- [x] On the episodes page, remove the three dots on the top right, and replace it with 

Button in episode page             |  Button in downloads page 
:-------------------------:|:-------------------------:
<img width="296" alt="capture d ecran 2018-02-07 a 15 52 29" src="https://user-images.githubusercontent.com/22198043/35941057-12e8dcfe-0c1f-11e8-86ab-a5339fa7bc65.png">|<img width="296" alt="capture d ecran 2018-02-07 a 15 52 15" src="https://user-images.githubusercontent.com/22198043/35941074-17a30a1c-0c1f-11e8-9865-1887d0fe895f.png">

- [x] Take the create ACTION_DOWNLOAD_PAGE and relate it to the button in the downloads page.
 
### Related to this story 

- commit: #56  

### Unit test: 

- commit: #57 

### Demo steps: 

1. Go to the "Episodes" page by clicking on the tab "Episodes" in the menu 
2. Click on the top right icon (shown in the picture) 

<img width="305" alt="capture d ecran 2018-02-14 a 13 43 41" src="https://user-images.githubusercontent.com/22198043/36222115-47299372-118e-11e8-8439-6a58ce6caa12.png">

4. Select the episodes you want to modify
5. Once you are done with your selection, click on the button with the action you want to do on those episodes, on the action bar (in the bottom). 

<img width="304" alt="capture d ecran 2018-02-14 a 13 44 01" src="https://user-images.githubusercontent.com/22198043/36222160-721bc2da-118e-11e8-83a5-f62a3de8dfd6.png">

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by Cotso** [comment]
![uml episodes page](https://user-images.githubusercontent.com/15900901/36512237-8d64a90e-1737-11e8-8f8b-482a9215d317.png)

[UML Diagram can be found here](https://www.lucidchart.com/documents/edit/1f97e1de-8d06-404c-9a08-1b7743b0cf13/0)

UML class diagram done by @jiggy357.
