### ISSUE TITLE
Story: Preferences

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#43]
## As a user I want to be able to have my preferences stored so that I can have a preferences profile in the app.

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Medium
- _**Estimation of the ideal time**_: 6 hours

### Tasks TO DO: 

- [x] Create a tab "Preferences" or create a page "Preferences" in the settings 
- [x] Be able to save different kinds of categories of podcasts 

### Related to this story 

- commit: #77 

### Unit test & UI test

- commit: #77  

### Demo steps 

1. Open side menu
2. Click on "Settings" 

<img width="305" alt="capture d ecran 2018-03-20 a 17 32 55" src="https://user-images.githubusercontent.com/22198043/37733193-abb66c2a-2d1d-11e8-9215-2248f9d5eb9d.png">

3. Click on "Select your Categories preferences" 

<img width="307" alt="capture d ecran 2018-03-20 a 17 33 08" src="https://user-images.githubusercontent.com/22198043/37733224-c24ce90a-2d1d-11e8-9b5a-0544823bfc6f.png">

4. Select the Categories you prefer 

<img width="303" alt="capture d ecran 2018-03-20 a 17 36 58" src="https://user-images.githubusercontent.com/22198043/37733251-de553634-2d1d-11e8-8fcd-821577298fbb.png">
 
5. Click on "confirm" once you are done selecting the categories

[Click here to see the demo steps video](https://www.youtube.com/watch?v=vu8tMdVDJjQ&feature=youtu.be) 
Video done by @LeCleric 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by ghost** [comment]
c518fd7
bb4d35d
a0e7805
ecd858b

**Comment by guipadua** [comment]
Based on the video, works fine.

**Comment by ghost** [comment]
![antennapod core preferences userpreferences](https://user-images.githubusercontent.com/22198043/37944245-d981f1b8-3148-11e8-949d-b0d9ed551d8e.png)

[Can be found by clicking here.](https://www.lucidchart.com/invitations/accept/ae5952f9-e5f2-4001-8844-32e51bf150d6) 

![capture d ecran 2018-03-26 a 21 50 27](https://user-images.githubusercontent.com/22198043/37944329-1525e3d2-3149-11e8-977e-2571b76b890e.png)

[Can be found by clicking here.](https://www.lucidchart.com/invitations/accept/043fab31-4090-421e-9091-7e477c784a8f)

**Comment by ghost** [comment]
Ui test "testDiscoveryPreferences()" passes: 

<img width="1278" alt="capture d ecran 2018-03-26 a 23 00 21" src="https://user-images.githubusercontent.com/22198043/37944443-97524e72-3149-11e8-9207-ff15da12c65f.png">
