### ISSUE TITLE
Story: Discovery tab 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#44]
## As a user I want to be able to have a Discovery page so that I can have recommendations according to my preferences (entered in my preferences profile). 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Medium
- _**Estimation of the ideal time**_: 8 hours

### Tasks TO DO: 

- [x] Create the "Discovery" tab in the menu
- [x] If the user already completed his preferences profile, use them to find the best (according to the ratings) related to the categories selected. 

_If the user has not already completed his preferences profile, ask him to do so and put a button leading to where he can do it._ **TODO another time -- for now, the default page is the same as the trending page.**

### Related to this story 

- commit: #77  

### Unit test 

- commit: #77 

### Demo steps 

1. Go to the "Discovery page" by clicking on the tab "Discovery" in the menu

<img width="305" alt="capture d ecran 2018-03-20 a 17 32 55" src="https://user-images.githubusercontent.com/22198043/37684074-1959bed0-2c65-11e8-8b5d-c0888ede81ca.png">

2. Enjoy discovering the trending podcasts according to your taste in your preferences in the settings page.  

![capture d ecran 2018-03-20 a 01 30 10](https://user-images.githubusercontent.com/22198043/37684219-b47e8602-2c65-11e8-8753-bb9675d83dda.png)

[Click here to see the demo steps video](https://www.youtube.com/watch?v=vu8tMdVDJjQ&feature=youtu.be) 
Video done by @LeCleric

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by Raph1105** [comment]
I am going to work on that.

**Comment by ghost** [comment]
c518fd7 
032d187
5258bc4
9683f32
40350c2

**Comment by guipadua** [comment]
Video looks fine. Just didn't show (neither described here - although I saw the note for future work) what happen now when the categories were not previously selected.

**Comment by FrankSauve** [comment]
@guipadua The page is empty if no categories are chosen for now. This could be changed to have a message saying something like "Go to preferences to add categories you like"

**Comment by ghost** [comment]
![capture d ecran 2018-03-26 a 21 46 25](https://user-images.githubusercontent.com/22198043/37944507-deb1aca4-3149-11e8-970c-0b9f6aaba536.png)

[Can be viewed by clicking here.](https://www.lucidchart.com/invitations/accept/1240ee82-cc0e-4082-8b20-b98a40034202)

**Comment by ghost** [comment]
Ui test passes: 

<img width="1280" alt="capture d ecran 2018-03-26 a 23 13 50" src="https://user-images.githubusercontent.com/22198043/37944866-65148568-314b-11e8-92af-0e0af035c5fa.png">
