### ISSUE TITLE
Story: Create folders 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#45]
## As a user, I want to be able to create folders (and name them), so that I organize my podcasts.

- **Number of story points:** 13
- **Priority:** Medium 
- **Risk:**  High
- _**Estimation of the ideal time**_: 10 hours

### Tasks TO DO: 

- [x] Create Folders Fragment
- [x] Add Folders Fragment to side menu
- [x] Create appropriate view for the fragment
- [x] Add create folder functionality
- [x] Add naming functionality

### Related to this story 

- commit: #75

### Unit test

- commit: #75

### UI test

- commit: #80 

### Demo steps 

1. Open side menu
2. Click on "My Folders" 
3. Click on "Add Folder" 
4. Enter the name for your new folder 
5. Click on "OK"

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [ ] Get TA signoff

**Comment by williamkingbede** [comment]
UI test for this story passed:
![capture d ecran 42](https://user-images.githubusercontent.com/25252961/37934905-c891d0e2-311d-11e8-8539-f6a123c56ade.png)

**Comment by williamkingbede** [comment]
![capture d ecran 43](https://user-images.githubusercontent.com/25252961/37936931-7b951d78-3125-11e8-9f67-0c0b469eb40c.png)
[UML Diagram can be found here](https://www.lucidchart.com/documents/edit/1f97e1de-8d06-404c-9a08-1b7743b0cf13/0)

UML class diagram done by @jiggy357.

**Comment by guipadua** [comment]
Do you have a video for this one?

**Comment by LeCleric** [comment]
@guipadua Since there are still the additional steps required to make the folders appear I didn't put up a video.

Here's a video of the story in its current state:
https://www.youtube.com/watch?v=_4Ba1z7HdCA&feature=youtu.be

Fulfills all of the tasks in the story, but for now it requires you to press *Add Folder* followed by *Cancel* to make your folder appear.

Once the folders appear automatically I'll put that video up on the issue itself instead of the comments.
