### ISSUE TITLE
Story: Add podcasts to folders

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#46]
## As a user, I want to be able to add podcasts (from the episodes page) into the folders that I have created, so that I can populate them.

- **Number of story points:** 7
- **Priority:** Medium
- **Risk:** Medium
- _**Estimation of the ideal time**_: 10 hours

### Tasks TO DO: 

- [x] Create menu option to add items to folders in EpisodesApplyActionFragment
- [x] Add function to add items to folders
- [x] Create relationship between feeditems and folders
- [x] Create new fragment that will display items from a folder
- [x] Ensure that items displayed in fragment are those that were added to the folder

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [x] Get TA signoff 

### Related to this story 

- commit: #106 
- commit: #112 

### Unit test

- commit: #112 

### UI test

- commit: #112 

### Demo Video
https://youtu.be/UmSpcNy8wGE

### Demo Steps
1. Ensure that you are subscribed to a feed.
2. Ensure that a folder is created.
3. Click in “Episodes”.
4. Click on “All”.
5. Click on three gears icon located on the top right corner.
6. Select items to add.
7. Click on three dots located on top right corner. 
8. Select folder where items will be added.

**Comment by Sarb-F** [comment]
#46
![screen shot 2018-03-27 at 11 39 02 am](https://user-images.githubusercontent.com/11098366/37978314-c5d6cef2-31b3-11e8-820d-6a671e9b7151.png)

**Comment by williamkingbede** [comment]
### Good To Know:
- Episodes already added to one folder cannot be added to another
- If you add a lot of episodes at once to a folder it will take time to load all of them (Check the triangle counter)

**Comment by Raph1105** [comment]
Is this done ?

**Comment by Raph1105** [comment]
@jiggy357 @williamkingbede is this story ready for sign off ?

**Comment by ghost** [comment]
@guipadua can you sign off this story? thank you.

**Comment by williamkingbede** [comment]
UI test successfully passed.
![capture d ecran 49](https://user-images.githubusercontent.com/25252961/38567845-28ca228c-3cb5-11e8-9314-ed797565c0ef.png)

**Comment by guipadua** [comment]
Video looks fine for ideal scenario. Was it just the one UI test for adding? Maybe you could are a bit more, more scenarios (for example, with multiple episodes in multiple folders to see if they don't get mixed up).
