### ISSUE TITLE
Story: Folders tab 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#47]
## As a user, I want to be able to see my folders in the menu, so that I can access them easily. 
- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Medium
- _**Estimation of the ideal time**_: 5 hours

### Tasks TO DO: 

- [x] Add Folders tab in the side menu when a user creates it 
- [ ] Be able to rename or delete the folders from the side menu

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write UI tests
- [ ] Write demo steps 
- [ ] Get TA signoff 

### Demo Video
https://youtu.be/UmSpcNy8wGE
