### ISSUE TITLE
Story: Search page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#48]
## As a user, I want to have a Search page (populated by iTunes), so that I can search podcasts. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:**  Medium
- _**Estimation of the ideal time**_: 10 hours

### Tasks TO DO: 

- [ ] task1

### TO DO before closing the issue: 
- [ ] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by FrankSauve** [comment]
I don't think this story is necessary. See #49 
Closing it for now
