### ISSUE TITLE
Story: Advanced search page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#49]
## As a user, I want to be able to, in the search page, seek for podcasts by category, language, artist (and date) so that I can easily find what I am looking for specifically. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:**  Medium
- _**Estimation of the ideal time**_: 15 hours

### Tasks TO DO: 

- [x] Create advanced search options items in iTunes search page
- [x] Extend the search function to search by **category**
- [x] Extend the search function to search by **artist**
- [x] Extend the search function to search by **language**
- [x] Extend the search function to search by **title**

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff 

### Demo Steps

1. Open the side menu
2. Click on the **Add Podcast** tab
3. Click on the **Search ITunes** option
4. Open Advanced Search menu (top right hand corner)
5. Select one of the search options
6. Podcasts will be displayed according to the search option selected

**Comment by williamkingbede** [comment]
![capture d ecran 28](https://user-images.githubusercontent.com/25252961/36950360-dd1d0d5e-1fc2-11e8-8e22-264942558615.png)
[View in Lucidchart](https://www.lucidchart.com/documents/edit/1f97e1de-8d06-404c-9a08-1b7743b0cf13/0)
UML class diagram done by @jiggy357.

**Comment by guipadua** [comment]
Demoed and it worked. It has unit tests in the emulator structure.

**Comment by ghost** [comment]
@williamkingbede can you put the proof that the  Ui tests pass? please
