### ISSUE TITLE
Update the UML class Diagram - R2

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#50]
## Update the UML Class Diagram with the new features implemented 

- [x] Story: Advanced search page #49
- [x] Story: Preferences #43
- [x] Story: Discovery tab #44
- [x] Story: Sub-Categories on the window #54 
- [x] Story: Autocomplete suggestions #68 
- _Story: Folders tab #47 -- moved for I5_
- _Story: Add podcasts to folders #46 -- moved for I5_
- [x] Story: Create folders #45 

**We have to link each UML class diagrams to its Story**
