### ISSUE TITLE
Story: Organize the settings page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#52]
## As a user, I want to be able to have a user-friendly settings page, so that I can find what I am looking for easily.

- **Number of story points:** 5 
- **Priority:** Low
- **Risk:**  Medium
- _**Estimation of the ideal time**_ : 3 hours

### Tasks TO DO: 

- [x] Think about subcategories for the settings page (eg. "Presentation settings", "Downloading settings" ...). 
- [x] Create those subcategories and put the corresponding existing settings in it (to have a more organize view). 

### Related to this story 

- commit: #105
- commit: #108   

### Ui test 

- commit: #108 

![capture d ecran 2018-04-08 a 16 53 51 2](https://user-images.githubusercontent.com/22198043/38472411-a5d614b6-3b4d-11e8-881c-dc2cfb5566b5.png)

### Demo steps 

[Click here to see the new, improved settings page](https://www.youtube.com/watch?v=RCAqYFX-0fI&feature=youtu.be) 
[Click here to see the old settings page](https://www.youtube.com/watch?v=xMeFjG_xws0&feature=youtu.be) 
Video done by @LeCleric

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- _Write unit tests **(Not applicable)**_
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by ghost** [comment]
#105

**Comment by ghost** [comment]
@guipadua can you sign off this story ? thank you.

**Comment by guipadua** [comment]
Nice, much better. Just small thing above, that was UI test, not unit. I see you updated many tests since this change the UI a lot.

**Comment by ghost** [comment]
@guipadua I am confused, where did I say it was a Unit test? 

I feel that it is not really necessary to do a unit test since I did not add any functions... I only played with the interface.  

Do you need me to do something else than what I did for the Ui tests?

**Comment by guipadua** [comment]
No, it was just the description of the story on the top of this issue. Looks good now.
