### ISSUE TITLE
Story: Sub-categories on the window

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#54]
##  As a user, I want to have a sub-categories displayed on the window so I can find new podcasts of a specific genre.

- **Number of story points:** 8
- **Priority:** High
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 3 hours

### Tasks TO DO: 

- [x] Show subcategories when the user selects a category in advanced search

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps (In the advanced Search Feature issue #33 )
- [x] Get TA signoff

**Comment by guipadua** [comment]
Demoed and it worked. It has unit tests in the emulator structure.

**Comment by ghost** [comment]
@FrankSauve @LeCleric Can you guys link the UML Class diagram updates and the Ui test proof? Thank you.

**Comment by LeCleric** [comment]
UI test proof is on its own issue #69 
Here it is again though

![image](https://user-images.githubusercontent.com/13441191/38143009-9eeea75a-340c-11e8-9362-29317c3fe4c4.png)
