### ISSUE TITLE
Update the UML class Diagram - I4

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#58]
## Update the UML Class Diagram with the new features implemented 

- [ ] Story: Organize the settings page #52
- [ ] Story: Fix or delete non-working features #51
- [ ] Story: Folders tab #47
- [ ] Story: Add podcasts to folders #46
- [ ] Story: Create folders #45

**We have to link each UML class diagrams to its Story**
