### ISSUE TITLE
Story: Autocomplete suggestions

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#68]
## As a user, I want to have suggestions in the search bar, so I can be more productive in my research. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 5 hours

### Tasks TO DO: 

Load search results on text change as auto-completion for:
- [X] Regular search
- [x] Title search
- [x] Artist search

### DEMO steps: 

[Click here to see the demo steps video](https://www.youtube.com/watch?v=r6hpLT96S3E&feature=youtu.be) 
Video done by @LeCleric

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI test
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by guipadua** [comment]
Video looks fine. It is just not yet clear to me how to activate the autocomplete, is it just to wait or press something?
Either way it can be signed off.

**Comment by FrankSauve** [comment]
@guipadua Just like google autocomplete, the suggestions are loaded every time the user types a character. It looks strange in the video because the person doing the demo was typing faster than the autocomple requests

**Comment by LeCleric** [comment]
Yeah, I've got a fairly high wpm when using a keyboard.
On mobile no one would be able to type that quickly.

**Comment by FrankSauve** [comment]
# UI Tests

## Regular Search
![image](https://user-images.githubusercontent.com/13418355/37940452-aa9fa0aa-3136-11e8-8d31-e64aeaf6828e.png)

## Title Search
![image](https://user-images.githubusercontent.com/13418355/37940478-cfabf40c-3136-11e8-94e0-eaa2d5b2da7d.png)

## Artist Search
![image](https://user-images.githubusercontent.com/13418355/37940505-fe0eaccc-3136-11e8-810f-8f99c3bfe810.png)

**Comment by FrankSauve** [comment]
# Arch Diagram for ItunesSearchFragment
![image](https://user-images.githubusercontent.com/13418355/37940773-81c262f6-3138-11e8-8ad6-be5286501466.png)
