### ISSUE TITLE
Story: "Recommended for you" checkbox in preferences

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#81]
## As a user, I want to have a "Recommended for you" function in the preference page, so I can decide if I want to have automatic or manual suggestions

- **Number of story points:** 3
- **Priority:** Low
- **Risk:**  Medium
- _**Estimation of the ideal time**_: 7 hours

### Tasks TO DO: 

- [x] Create a checkbox in the preferences to enable the feature and disable manual suggestions.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI test
- [x] Write demo steps 
- [x] Get TA signoff 

### DEMO steps: 

**Prerequisite: Subscribe to a podcast**

[Click here to see the demo steps video. This story is from 0:00 to 0:22](https://www.youtube.com/watch?v=fy0RVscoJbU) 
Descriptions of what is happening are in the video description.
Video done by @LeCleric

1. Click on settings
![image](https://user-images.githubusercontent.com/13418355/38396960-0351764a-3909-11e8-88cc-e39b958da128.png)

2. Click on "Select you categories preference"
![image](https://user-images.githubusercontent.com/13418355/38396998-360bc1da-3909-11e8-93f1-70baeb124c31.png)

3.1  **FAILING STEP: Select "Automatic recommendations" and a category, then click confirm. The system will display an error message.**
![image](https://user-images.githubusercontent.com/13418355/38397038-6e7a2ebc-3909-11e8-831c-332bd7e84e51.png)
![image](https://user-images.githubusercontent.com/13418355/38397060-86815512-3909-11e8-81f4-ab77211671da.png)

3.2 **NORMAL STEP: Click only on automatic recommendation**
![image](https://user-images.githubusercontent.com/13418355/38397137-e35b4298-3909-11e8-95ce-acb12a9b8316.png)

**Comment by FrankSauve** [comment]
## UI test passed
![image](https://user-images.githubusercontent.com/13418355/38457134-843065c6-3a5a-11e8-9331-bcf0b1e0a7c9.png)

**Comment by ghost** [comment]
@guipadua can you sign off this story ? thank you.

**Comment by guipadua** [comment]
In the video looks fine. Another option added. Make sure you test the error message.

**Comment by LeCleric** [comment]
Architecture Diagram on #79
