### ISSUE TITLE
Story: Delete folder 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#82]
## As a user, I want to be able to delete a folder so I do not have unnecessary folders in my app. 

- **Number of story points:** 5 
- **Priority:** Medium
- **Risk:**  Medium
- _**Estimation of the ideal time**_ : 5 hours

### Tasks TO DO: 

- [x] Create function to delete folders
- [x] Add function to delete folder and its episodes with context click
- [x] Add function to delete folder from menu inside folder

### Related to this story 

- commit: #111 
- commit: #121 

### Unit test

- commit: #111

### UI test

- commit: #111 

### Demo steps 

0. Create a folder (see demo steps in #45)
1. Open side menu
2. Click on "My Folders" 
3. Long click on one of the folders to open context menu  
4. Select "Remove Folder"

### Extension:
3. a. Click on one of the folders
3. b. Click on the three dots on top menu options

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by williamkingbede** [comment]
UI test passed.
![capture d ecran 46](https://user-images.githubusercontent.com/25252961/38471127-e29fd8e0-3b3a-11e8-9fbf-35500ef424e2.png)

**Comment by williamkingbede** [comment]
Extented UI test passed.
![capture d ecran 48](https://user-images.githubusercontent.com/25252961/38471470-7c4c17a2-3b3f-11e8-8e64-7c80c6d7f5b1.png)

**Comment by guipadua** [comment]
Works, folder is deleted. Has tests.
