### ISSUE TITLE
Story: Delete episode in folder

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#83]
## As a user, I want to be able to delete episodes in a folder so I do not have unwanted episodes in my folder.

- **Number of story points:** 5 
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 5 hours

### Tasks TO DO: 

- [x] Create a dialog box to rename the folders

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [ ] Get TA signoff 

### Demo Steps

Folders must be created with episodes added to them.

1. Open side bar.
2. Select a folder to remove episodes from.
3. Click on three gears icon located on top right corner.
4. Select episodes to be removed.
5. Click on trash can icon located on bottom right corner.

**Comment by Sarb-F** [comment]
#83
![blank diagram - page 1-4](https://user-images.githubusercontent.com/11098366/38974359-d14149d6-4377-11e8-9d36-7fc0577f517c.jpeg)
