### ISSUE TITLE
Story: Rename folder

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#84]
## As a user, I want to be able to rename a folder so I can be more or less specific in the name of my folder.

- **Number of story points:** 5 
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 5 hours

### Tasks TO DO: 

- [x] Add rename podcast button
- [x] Create function to rename podcasts

**Related to this story**

- Commit #122 

**UI Test**

- Commit #122 

**Demo Steps**

0.  Create a folder
1.  Open side menu
2.  Click on "My Folders"
3.  Long click on the desired folder
4.  Click "Rename Folder"

**Extensions**

   3.a.  Click on the desired folder
   4.a.  Click on the three dots in the top right corner
   5.a.  Click on "Rename Folder"

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [ ] Get TA signoff

**Comment by Sarb-F** [comment]
#84
![rename folder passing test](https://user-images.githubusercontent.com/11098366/38958281-ca81aa02-432a-11e8-91ac-0c0da32ab022.png)

**Comment by Sarb-F** [comment]
#84
Renaming folder with items in it
![rename folder with items passing unit test](https://user-images.githubusercontent.com/11098366/38958637-d920c09c-432b-11e8-9d28-0b6cf4c2536c.png)

**Comment by ghost** [comment]
#125

**Comment by Sarb-F** [comment]
#84
UML
![screen shot 2018-04-19 at 2 33 54 am](https://user-images.githubusercontent.com/11098366/38975051-5133821a-437a-11e8-901d-34668e30ff3f.png)
