### ISSUE TITLE
Feature: Manage folders

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#85]
## Feature Description

Have many options for folders, such as delete it, delete episodes in the folder, rename folder and change the order of listening of the episodes in the folder. 

## Feature Stories

- [x] As a user, I want to be able to delete a folder so I do not have unnecessary folders in my app. #82
- [x] As a user, I want to be able to delete episodes in a folder so I do not have unwanted episodes in my folder. #84
- [x] As a user, I want to be able to rename a folder so I can be more or less specific in the name of my folder. #83

**Comment by ghost** [comment]
@guipadua Can you please validate this feature? Thank you.
