### ISSUE TITLE
Story: Change the order of the episodes in a folder

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#86]
## As a user, I want to be able to change the order of the episodes in my folder, so I can listen to a specific order of my episodes. 

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 3 hours

### Tasks TO DO: 

- [ ] Change the layout of folders so that its possible to drag them up and down.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by ghost** [comment]
This story was removed due to the lack of time and some functionality problems.
