### ISSUE TITLE
Story: Automatically share on Twitter

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#89]
## As a user, I want to be able to post automatically on Twitter whenever I listene to a podcast, so I can share it to my Twitter friends. 

- **Number of story points:** 5
- **Priority:** Low 
- **Risk:**  Medium 
- _**Estimation of the ideal time**_ : 7 hours

### Tasks TO DO: 

- [x] Add login to twitter in settings
- [x] Post to twitter on listen

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by FrankSauve** [comment]
## Demo Steps
[Successful login + automatic tweets enabled (Tweet appears)](https://www.youtube.com/watch?v=aFimX0-ZIQo&feature=youtu.be)
[Successful login + automatic tweets disabled (Tweet should not appear)](https://www.youtube.com/watch?v=yjWNR10W4Ao)

**Comment by FrankSauve** [comment]
I am unable to mock anything from the twitter api. This makes it almost impossible to build unit tests for this feature.
![image](https://user-images.githubusercontent.com/13418355/38769538-ab753d50-3fd2-11e8-95ab-6a89685e36a5.png)

**Comment by FrankSauve** [comment]
Unit test passed
![image](https://user-images.githubusercontent.com/13418355/38769910-903903f4-3fd8-11e8-8366-207d2e29c36d.png)

**Comment by guipadua** [comment]
Looks good. Has unit tests, but some functionality with twitter didn't fully work for testing purposes.
