### ISSUE TITLE
Story: Suggest podcast based on what was previously listened

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#90]
## As a user, I want to see suggested podcast based on what I have subscribed to previously. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 4 hours 

### Tasks TO DO: 

Create algorithm to suggest podcast based on what the user listened to previously:
- [x] By artists
- [x] By category
- [x] By title
- [x] Display the suggestions in the discover view
- [ ] Remove duplicate podcasts
- [x] Remove the podcast in the query

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write UI test
- [x] Write demo steps 
- [x] Get TA signoff 

## Demo Steps
**Prerequisites:** 
- Subscribe to a podcast
- Select "Automatic Recommendations" in settings (see #81 demo steps)

[Click here to see the demo steps video. This story is from 0:22 to 1:20](https://youtu.be/fy0RVscoJbU?t=22s) 
Descriptions of what is happening are in the video description.
Video done by @LeCleric

1. Go to discovery tab
![image](https://user-images.githubusercontent.com/13418355/38397169-2ea3e66a-390a-11e8-87da-053a18e29356.png)

2. See similar podcast to a subscribed podcast
![image](https://user-images.githubusercontent.com/13418355/38397178-462e1e5e-390a-11e8-9e13-2bc4f1ced5fb.png)

**Comment by FrankSauve** [comment]
## UI test passed
![image](https://user-images.githubusercontent.com/13418355/38457134-843065c6-3a5a-11e8-9331-bcf0b1e0a7c9.png)

**Comment by ghost** [comment]
@guipadua can you sign off this story ? thank you.

**Comment by guipadua** [comment]
In the video, it seems to work based on a single selection, which happens randomly each time the discovery is opened. Maybe could be also a mix of previous items in another story. This is good for now.
Is there unit test here as well, or just UI?

**Comment by FrankSauve** [comment]
@guipadua [Unit test is here](https://github.com/FrankSauve/390AntennaPod/blob/develop/app/src/androidTest/java/de/test/antennapod/discovery/DiscoveryTest.java)

**Comment by LeCleric** [comment]
Architecture Diagram on #79
