### ISSUE TITLE
Story: local search in episodes page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#92]
## As a user, I want to be able to search for a specific episode in my episodes page. 

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 8 hours

### Tasks TO DO: 

- [ ] task1

### TO DO before closing the issue: 
- [ ] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by ghost** [comment]
Unfortunately, we found that this features was already implemented. It was removed by mistake in the Second Sprint.

This story will be replaced by #115.
