### ISSUE TITLE
Feature: Home page 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#95]
## Feature Description

Have a homepage with an overview of the different pages of the app. 

## Feature Stories

- [x] As a user, I want a user-friendly home page, so I can have a lot grouped into one page. #102 
- ~~As a user, I want to be able to see 10 Trending podcasts on my home page, so I can access them easily. #96~~
- ~~As a user, I want to be able to see the 10 first podcasts from the discovery page on my home page, so I can access them easily. #98~~
- [x] As a user, I want to be able to see my favorite podcasts on my home page, so I can access them easily. #99 
- [x] As a user, I want to be able to see the most recent podcasts I have subscribed to on my home page, so I can access them easily. #100 
- [x] As a user, I want to be able to see my folders on my home page, so I can access them easily. #101

**Comment by ghost** [comment]
@guipadua Can you please validate this feature? Thank you.

**Comment by Sarb-F** [comment]
#95
UML
![blank diagram - page 1-3](https://user-images.githubusercontent.com/11098366/38972585-83b59ec2-436f-11e8-880f-d5d2685d704c.jpeg)
