### ISSUE TITLE
Story: Trending on home page 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#96]
## As a user, I want to be able to see 10 Trending podcasts on my home page, so I can access them easily.

- **Number of story points:** 13
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 5 hours 

### Tasks TO DO: 

- [ ] Load the trending podcast on the home page

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by ghost** [comment]
Unfortunately, this story will not be done due to complications and lack of time.
