### ISSUE TITLE
Story: Favorite episodes on home page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#99]
## As a user, I want to be able to see my favorite episodes on my home page, so I can access them easily.

- **Number of story points:** 3
- **Priority:** Low
- **Risk:**  Low
- _**Estimation of the ideal time**_ : 3 hours

### Tasks TO DO: 

- [x] Load the users favorite podcasts on the homepage

### Demo steps: 

1. go to homepage
2. see your favorites episodes 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write unit tests
- [x] Write demo steps 
- [x] Get TA signoff

**Comment by guipadua** [comment]
Demoed and it works.

**Comment by ghost** [comment]
#124 & a3f007b
